### ISSUE TITLE
Missing application/json Content-Type response header

### ISSUE THREAD

**Issue by davidbarratt** [wesleylima/ocfr-calls#2]
https://github.com/wesleylima/ocfr-calls/blob/3314d71bda786e8e94210611feb89650d6de4e66/index.js#L38-L43

It looks like Cloudflare expects the worker to respond with a [Response](https://developers.cloudflare.com/workers/reference/apis/response) object. I would construct a new one rather sending a plain object (which, I'm shocked works at all).

**Comment by wesleylima** [comment]
index.js is called from worker.js which then maps those keys to a Response object. Handled it this way for portability. Fixed the mapping of the headers to the response object.
