### ISSUE TITLE
Use cache everything on fetch to be kind to 3rd party

### ISSUE THREAD

**Issue by davidbarratt** [wesleylima/ocfr-calls#3]
https://github.com/wesleylima/ocfr-calls/blob/3314d71bda786e8e94210611feb89650d6de4e66/index.js#L30

Changing this to something like
```js
fetch(url, { cf: { cacheEverything: true } })
```
will cache the response in Cloudflare (according the the cache headers in the response).
https://developers.cloudflare.com/workers/templates/pages/cache_ttl/

**Comment by wesleylima** [comment]
Fixed
